### ISSUE TITLE
Ability to get random kid safe joke from API

### ISSUE THREAD

**Issue by bradp** [sylturner/Jokels#60]
Hey, implementing this into Hubot right now, but there doesn't seem to be a way to enable clean mode when hitting the api for a random joke.

I may be missing something obvious, thoughts?

**Comment by adamgriffis** [comment]
Right now this is a session variable I believe. I'll have to review the code -- I should be able to just add a parameter for you though, @bradp.

**Comment by bradp** [comment]
That would be awesome.

:+1:

**Comment by adamgriffis** [comment]
The fix for this issue has now been deployed - just add `?clean=true` to the endpoint in your hubot script, and you should only receive clean jokes from now on.

Just a heads-up - we use a gem (profanity filter -- https://github.com/intridea/profanity_filter) to detect profane jokes (and the honesty of users) but its possible for dirty ones to sneak into the clean list.

**Comment by bradp** [comment]
:boom: thanks!
